name: Sync

# è§¦å‘æ¡ä»¶ï¼šåœ¨ push åˆ° main åˆ†æ”¯å
on:
  push:
    branches:
      - main

# ä»»åŠ¡
jobs:
  build-and-deploy:
    # æœåŠ¡å™¨ç¯å¢ƒï¼šæœ€æ–°ç‰ˆ Ubuntu
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ” sync to Gitee
        uses: Yikun/hub-mirror-action@master
        with:
          src: github/KiyanYang
          dst: gitee/KiyanYang
          dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
          dst_token: ${{ secrets.GITEE_TOKEN }}
          # å¯é€‰, é…ç½®åä»…åŒæ­¥é™æ€åˆ—è¡¨ï¼Œä¸ä¼šå†åŠ¨æ€è·å–éœ€åŒæ­¥åˆ—è¡¨ï¼ˆé»‘ç™½åå•ä¾æ—§ç”Ÿæ•ˆï¼‰ï¼Œå¦‚â€œrepo1,repo2,repo3â€ã€‚
          static_list: "HashTool"
          force_update: true
